-- CreateEnum
CREATE TYPE "EventType" AS ENUM ('APPLICATION', 'INTERVIEW', 'SCHEDULE_REQUEST', 'FOLLOW_UP', 'OFFER', 'REJECTION', 'WITHDRAWAL');

-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "type" "EventType" NOT NULL DEFAULT 'APPLICATION';
